export const FETCH_CANDIDATES = 'FETCH_CANDIDATES';
export const FETCH_CANDIDATES_ERROR = 'FETCH_CANDIDATES_ERROR';
export const FETCH_CANDIDATES_LOADING = 'FETCH_CANDIDATES_LOADING';

export const FETCH_CANDIDATE = 'FETCH_CANDIDATE';
export const FETCH_CANDIDATE_ERROR = 'FETCH_CANDIDATE_ERROR';
export const FETCH_CANDIDATE_LOADING = 'FETCH_CANDIDATE_LOADING';

export const CANDIDATES_INSERT = 'CANDIDATES_INSERT';
export const CANDIDATES_INSERT_LOADING = 'CANDIDATES_INSERT_LOADING';
export const CANDIDATES_INSERT_ERROR = 'CANDIDATES_INSERT_ERROR';

export const CANDIDATES_UPDATE = 'CANDIDATES_UPDATE';
export const CANDIDATES_UPDATE_LOADING = 'CANDIDATES_UPDATE_LOADING';
export const CANDIDATES_UPDATE_ERROR = 'CANDIDATES_UPDATE_ERROR';


export const CANDIDATES_DELETE = 'CANDIDATES_DELETE';
export const CANDIDATES_DELETE_LOADING = 'CANDIDATES_DELETE_LOADING';
export const CANDIDATES_DELETE_ERROR = 'CANDIDATES_DELETE_ERROR';

export const CANDIDATES_CANCEL = 'CANDIDATES_CANCEL';

export const EXPERIENCES_INSERT = 'EXPERIENCES_INSERT';
export const EXPERIENCES_INSERT_LOADING = 'EXPERIENCES_INSERT_LOADING';
export const EXPERIENCES_INSERT_ERROR = 'EXPERIENCES_INSERT_ERROR';

export const EXPERIENCES_UPDATE = 'EXPERIENCES_UPDATE';
export const EXPERIENCES_UPDATE_LOADING = 'EXPERIENCES_UPDATE_LOADING';
export const EXPERIENCES_UPDATE_ERROR = 'EXPERIENCES_UPDATE_ERROR';

export const EXPERIENCES_DELETE = 'EXPERIENCES_DELETE';
export const EXPERIENCES_DELETE_LOADING = 'EXPERIENCES_DELETE_LOADING';
export const EXPERIENCES_DELETE_ERROR = 'EXPERIENCES_DELETE_ERROR';
