export const FETCH_CANDIDATES = 'FETCH_CANDIDATES';
export const FETCH_CANDIDATES_ERROR = 'FETCH_CANDIDATES_ERROR';
export const FETCH_CANDIDATES_LOADING = 'FETCH_CANDIDATES_LOADING';

export const CANDIDATES_INSERT = 'CANDIDATES_INSERT';
export const CANDIDATES_INSERT_LOADING = 'CANDIDATES_INSERT_LOADING';
export const CANDIDATES_INSERT_ERROR = 'CANDIDATES_INSERT_ERROR';

export const CANDIDATES_UPDATE = 'CANDIDATES_UPDATE';
export const CANDIDATES_UPDATE_LOADING = 'CANDIDATES_UPDATE_LOADING';
export const CANDIDATES_UPDATE_ERROR = 'CANDIDATES_UPDATE_ERROR';


export const CANDIDATES_DELETE = 'CANDIDATES_DELETE';
export const CANDIDATES_DELETE_LOADING = 'CANDIDATES_DELETE_LOADING';
export const CANDIDATES_DELETE_ERROR = 'CANDIDATES_DELETE_ERROR';
